version: '3.5'

services:

  swag:
    image: linuxserver/swag
    container_name: swag
    depends_on:
      - wordpress
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=example@protonmail.com
      - URL=example.eu
      - SUBDOMAINS=www
      - VALIDATION=http
      - TZ=Europe/Berlin
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    extra_hosts:
      - "example.eu:127.0.0.1"
      - "www.example.com:127.0.0.1"
    volumes:
      - ./www:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_db_user
      WORDPRESS_DB_PASSWORD: wp_db_pass
      WORDPRESS_DB_NAME: wp_db_name
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MEMORY_LIMIT', '256M' );

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: wp_db_name
      MYSQL_USER: wp_db_user
      MYSQL_PASSWORD: wp_db_pass
